import { useState } from "react";
const SPEC = { name: "COIL_SYNC_PROTOCOL™", version: "v1.0", lastUpdated: "2026-05-01", status: "VERIFIED", superChunkSize: 5838, composition: [{ zone: "Header", bytes: 46, description: "Metadata: super_id, chunk_count, chunk_range, timestamp" },{ zone: "Hash Block", bytes: 640, description: "20 × 32-byte SHA256 chunk hashes (20 chunks × 256 bytes each)" },{ zone: "Payload", bytes: 5120, description: "20 × 256-byte raw data chunks" },{ zone: "Padding", bytes: 32, description: "Zero-fill to 5838 bytes (final SC of each file)" }], totals: { base: 5806, padded: 5838, chunksPerSC: 20, bytesPerChunk: 256 } };
const UPLOAD_FLOW = [{ step: 1, label: "generate_super_chunks.py", desc: "Read COIL_MASTER_CHIP.json → split into 256B chunks → pack 20 chunks into one .bin", icon: "⚙️" },{ step: 2, label: "batch upload", desc: "POST each .bin to /upload with fileId=COIL_MASTER_CHIP, super_id=N, Authorization header", icon: "📤" },{ step: 3, label: "server stores", desc: "Server writes chunks under fileId+super_id key, returns chunk count receipt", icon: "💾" },{ step: 4, label: "batch logging", desc: "Client appends receipt to COIL_BATCH_UPLOAD_LOG.json, advances cursor", icon: "📝" },{ step: 5, label: "/complete → reconstruct", desc: "Server reads all chunks, concatenates in super_id order, writes data/COIL_MASTER_CHIP.json", icon: "🔄" },{ step: 6, label: "SHA256 verify", desc: "Server returns SHA256 of reconstructed file; client compares to source hash", icon: "🔍" }];
const FAILURE_LOG = [{ task: "TASK 004", issue: "fileId mismatch mid-run (COIL_MASTER_CHIP vs COIL_MASTER_CHIP-1777394476)", cause: "Uploader switched target on resume, server stored chunks under wrong key", resolution: "Hard cleanup, manifest realignment, new run" },{ task: "TASK 005 (run 1)", issue: "fileId mismatch — same root cause as 004", cause: "Mid-resume fileId switch", resolution: "Cleaned up orphaned server chunks, realigned manifest" },{ task: "TASK 005 (run 2)", issue: "Reconstruction returned wrong size (4,659,650 vs 39,188,344)", cause: "Server wrote to wrong path or incomplete chunk set", resolution: "Server restarted, chunks re-uploaded from batch 1" },{ task: "TASK 005 (run 3)", issue: "HASH_LOCK triggered — 7,575 mismatches", cause: "Mirror daemon re-synced corrupted manifest during live run", resolution: "Daemon disabled; source data declared static and authoritative" }];
export default function Protocol() {
  const [activeTab, setActiveTab] = useState<"spec"|"flow"|"failures">("spec");
  return (
    <div className="min-h-screen bg-black text-white font-mono">
      <div className="max-w-5xl mx-auto p-8">
        <div className="flex items-center gap-3 mb-8"><span className="text-3xl">📡</span><div><h1 className="text-3xl font-bold tracking-tight">COIL SYNC PROTOCOL™</h1><p className="text-zinc-500 text-sm mt-1">The technical manual — reverse-engineered from 5838 bytes of binary.</p></div><span className="ml-auto px-3 py-1 bg-green-900 text-green-400 text-xs rounded border border-green-700">VERIFIED ✅</span></div>
        <div className="flex gap-2 mb-8 border-b border-zinc-800 pb-4">{["spec","flow","failures"].map(tab=>(<button key={tab} onClick={()=>setActiveTab(tab as typeof activeTab)} className={`px-4 py-2 text-sm rounded-t transition-colors ${activeTab===tab?"bg-zinc-800 text-white":"text-zinc-500 hover:text-white"}`}>{tab==="spec"?"SC Spec":tab==="flow"?"Upload Flow":"Failure Log"}</button>))}</div>
        {activeTab==="spec"&&(<div className="space-y-6"><div className="bg-zinc-900 border border-zinc-700 rounded p-6"><h2 className="text-lg font-bold text-cyan-400 mb-4">Super-Chunk Binary Format · 5838 Bytes</h2><div className="space-y-3">{SPEC.composition.map((zone,i)=>(<div key={i} className="flex items-start gap-4"><span className="text-xs text-zinc-500 w-20 shrink-0 mt-1">{zone.bytes}B</span><div className={`flex-1 p-3 rounded border ${i===0?"bg-cyan-950 border-cyan-800":i===1?"bg-purple-950 border-purple-800":i===2?"bg-green-950 border-green-800":"bg-zinc-800 border-zinc-700"}`}><span className="font-bold text-white">{zone.zone}</span><span className="text-zinc-400 text-sm ml-2">— {zone.description}</span></div></div>))}</div><div className="mt-4 pt-4 border-t border-zinc-700 grid grid-cols-2 md:grid-cols-4 gap-4 text-center">{[["46B","header"],["640B","hash block"],["5120B","payload"],["5838B","total per SC"]].map(([k,v])=>(<div key={k}><div className="text-2xl font-bold text-white">{k}</div><div className="text-xs text-zinc-500">{v}</div></div>))}</div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[["Chunks / SC","20"],["Chunk size","256B"],["SC base size","5,806B"],["SC padded size","5,838B"]].map(([k,v])=>(<div key={k} className="bg-zinc-900 border border-zinc-800 rounded p-4 text-center"><div className="text-2xl font-bold text-white">{v}</div><div className="text-xs text-zinc-500 mt-1">{k}</div></div>))}</div><div className="bg-zinc-900 border border-zinc-700 rounded p-5"><h3 className="font-bold text-yellow-400 mb-3">⚡ Critical Implementation Detail</h3><p className="text-sm text-zinc-300 leading-relaxed">The final super-chunk of every file is <span className="text-white font-bold">padded to 5838 bytes</span> with 32 zero-bytes. This is NOT a bug — it's a protocol requirement. The server expects all super-chunks to be exactly 5838 bytes.</p></div></div>)}
        {activeTab==="flow"&&(<div className="space-y-4"><p className="text-zinc-500 text-sm mb-4">End-to-end flow from source file to hash-verified reconstruction.</p>{UPLOAD_FLOW.map((step,i)=>(<div key={i} className="flex gap-4 items-start"><div className="w-8 h-8 rounded-full bg-zinc-800 border border-zinc-600 flex items-center justify-center text-sm font-bold shrink-0">{step.step}</div><div className="flex-1 bg-zinc-900 border border-zinc-700 rounded p-4"><div className="flex items-center gap-2 mb-1"><span>{step.icon}</span><span className="font-bold text-white">{step.label}</span></div><p className="text-sm text-zinc-400">{step.desc}</p></div></div>))}<div className="mt-6 p-4 bg-green-950 border border-green-800 rounded"><p className="text-green-400 text-sm">✅ TASK 005 — Full chain verified: source → 6,713 SCs → server → reconstruction → <span className="font-bold">SHA256 MATCH</span></p></div></div>)}
        {activeTab==="failures"&&(<div className="space-y-4"><p className="text-zinc-500 text-sm mb-4">Four failures. Four root-cause autopsies. One verified chain.</p>{FAILURE_LOG.map((f,i)=>(<div key={i} className="bg-zinc-900 border border-red-900 rounded p-5"><div className="flex items-center gap-2 mb-2"><span className="text-xs font-mono bg-red-900 text-red-300 px-2 py-0.5 rounded">{f.task}</span><span className="text-xs text-zinc-500">ISSUE</span></div><p className="text-white text-sm mb-3">{f.issue}</p><div className="grid md:grid-cols-2 gap-3 text-xs"><div><span className="text-zinc-500">Root cause: </span><span className="text-red-400">{f.cause}</span></div><div><span className="text-zinc-500">Resolution: </span><span className="text-green-400">{f.resolution}</span></div></div></div>))}</div>)}
        <div className="mt-12 pt-6 border-t border-zinc-800 text-xs text-zinc-600 flex justify-between"><span>COIL SYNC PROTOCOL™ · v1.0 · 2026-05-01</span><span>Derived from binary archaeology · COIL_UNBOUND</span></div>
      </div>
    </div>
  );
}
